version: '3'
networks:
  attendance-app-net:

services:
  attendance-app:
    build:
      context: .
    networks:
      attendance-app-net:
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - .:/workspace
    depends_on:
      - mysql
      - influxdb

  influxdb:
    image: influxdb:2.7.0
    ports:
      - "8086:8086"
    networks:
      attendance-app-net:
    env_file: .env

  mysql:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    networks:
      attendance-app-net:
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
